# Generated by Django 4.2.13 on 2024-05-20 15:10

from django.db import migrations

def create_habitats(apps, schema_editor):
    Habitat = apps.get_model('zoo_app', 'Habitat')
    Animal = apps.get_model('zoo_app', 'Animal')

    tropical_forest = Habitat.objects.create(name='Tropical Forest',image_url="../static/zoo_app/forest.jpeg")
    arctic = Habitat.objects.create(name='Arctic',image_url="../static/zoo_app/polar.jpeg")
    savannah = Habitat.objects.create(name='Savannah',image_url="../static/zoo_app/savannah.webp")

    Animal.objects.create(name='Penguin', species='Bird', age=5, breed='Emperor', health_status='Healthy', habitat=arctic)
    Animal.objects.create(name='Lion', species='Mammal', age=8, breed='African Lion', health_status='Healthy', habitat=savannah)

class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(create_habitats),
    ]
