# Generated by Django 4.2.13 on 2024-05-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0002_auto_20240520_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitat',
            name='image_url',
        ),
        migrations.AddField(
            model_name='habitat',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
