# Generated by Django 4.2.13 on 2024-05-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0003_remove_habitat_image_url_habitat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitat',
            name='location',
        ),
    ]
