# Generated by Django 4.2.13 on 2024-05-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0004_remove_habitat_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitat',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
