# Generated by Django 4.2.13 on 2024-05-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0007_auto_20240522_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('Lion', 'Lion'), ('Tiger', 'Tiger'), ('Elephant', 'Elephant'), ('Polar Bear', 'Polar Bear'), ('Gorilla', 'Gorilla'), ('Cheetah', 'Cheetah'), ('Walrus', 'Walrus'), ('Orangutan', 'Orangutan'), ('Zebra', 'Zebra'), ('Seal', 'Seal'), ('Leopard', 'Leopard'), ('Penguin', 'Penguin')], max_length=200),
        ),
    ]
