# Generated by Django 4.2.13 on 2024-05-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0008_alter_animal_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('group_type', models.CharField(max_length=200)),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_app.habitat')),
            ],
        ),
    ]
