# Generated by Django 4.2.13 on 2024-05-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0012_interaction_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zoo_app.animal'),
        ),
    ]
